### ISSUE TITLE
.gptignore should appropriately interpret leading slashes

### ISSUE THREAD

**Issue by dhnaranjo** [mpoon/gpt-repository-loader#40]
Given an ignore file of
```
/this_directory
```

Git will ignore the directory, this tool will include it. It'd be rad if they were consistent.

**Comment by JungeWerther** [comment]
totally, how do you ignore folders at the moment? can't seem to get it to work with ./folder or folder/ - am I doing something wrong?

**Comment by hfvienna** [comment]
This is how you can ignore folders. Requires an updated should_ignore method as well as an updated entry in .gptignore https://chat.openai.com/share/07238a64-c9af-4224-a1ca-04bbab60e07a

**Comment by jameshgrn** [comment]
@hfvienna @JungeWerther FWIW, the solution worked well for me!

**Comment by dep** [comment]
> This is how you can ignore folders. Requires an updated should_ignore method as well as an updated entry in .gptignore https://chat.openai.com/share/07238a64-c9af-4224-a1ca-04bbab60e07a

@hfvienna This 404s for me. Any help?

**Comment by hfvienna** [comment]
Also can't access it, likely has been deleted.
Don't remember this tbh.
I made my repository public, maybe you find the snippets:
https://github.com/hfvienna/gpt-repository-loader
Otherwise, or additionally, your best bet is to put the code and above
keywords and ask GPT-4 again.
Good luck.

Am Do., 30. Mai 2024 um 14:56 Uhr schrieb Danny Peck <
***@***.***>:
